version = 0.1

[default]
[default.global.parameters]
stack_name = "task-manager-api"
s3_bucket = "task-manager-deployments"
s3_prefix = "task-manager"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
image_repositories = []

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
stack_name = "task-manager-api"
s3_bucket = "task-manager-deployments"
s3_prefix = "task-manager"
region = "us-east-1"
parameter_overrides = "Environment=dev"
image_repositories = []
